plugins:
  - rubocop-performance
AllCops:
  TargetRubyVersion: 3.3.3
  # RuboCop has a bunch of cops enabled by default. This setting tells RuboCop
  # to ignore them, so only the ones explicitly set in this file are enabled.
  DisabledByDefault: false
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - "**/templates/**/*"
    - "**/vendor/**/*"
    - "bin/**/*"
    - "config/**/*"
    - "config.ru"
    - "db/**/*"
    - "actionpack/lib/action_dispatch/journey/parser.rb"
    - "railties/test/fixtures/tmp/**/*"
    - "actionmailbox/test/dummy/**/*"
    - "actiontext/test/dummy/**/*"
    - "**/node_modules/**/*"

Performance:
  Enabled: true
  Exclude:
    - "**/test/**/*"

Lint:
  Enabled: true

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Layout/EmptyLinesAroundClassBody:
  Enabled: false

Layout/EmptyLinesAroundModuleBody:
  Enabled: false

Layout/LineLength:
  Enabled: false # or explicit Max: 160 for example

Lint/AmbiguousBlockAssociation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - "spec/**/*"

Style/TrailingCommaInHashLiteral:
  Enabled: false
